/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tree;

/**
 *
 * @author Mahedi Hasan
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Delete_Tree = new javax.swing.JButton();
        Add_Tree = new javax.swing.JButton();
        Update_Tree = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        Delete_Tree.setBackground(new java.awt.Color(0, 102, 51));
        Delete_Tree.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Delete_Tree.setText("Delete Tree");
        Delete_Tree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Delete_Tree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete_Tree.setFocusable(false);
        Delete_Tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_TreeActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_Tree);
        Delete_Tree.setBounds(330, 280, 170, 50);

        Add_Tree.setBackground(new java.awt.Color(0, 102, 51));
        Add_Tree.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Add_Tree.setText("Add Tree");
        Add_Tree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Add_Tree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Tree.setFocusPainted(false);
        Add_Tree.setFocusable(false);
        Add_Tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_TreeActionPerformed(evt);
            }
        });
        jPanel1.add(Add_Tree);
        Add_Tree.setBounds(330, 140, 170, 50);

        Update_Tree.setBackground(new java.awt.Color(0, 102, 51));
        Update_Tree.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Update_Tree.setText("Update Tree");
        Update_Tree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Update_Tree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update_Tree.setFocusable(false);
        Update_Tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_TreeActionPerformed(evt);
            }
        });
        jPanel1.add(Update_Tree);
        Update_Tree.setBounds(330, 210, 170, 50);

        Logout_btn.setBackground(new java.awt.Color(0, 102, 51));
        Logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tree/logoutIcon.png"))); // NOI18N
        Logout_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Logout_btn.setIconTextGap(7);
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Logout_btn);
        Logout_btn.setBounds(730, 10, 90, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tree/Tree-icon.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 3, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 10, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tree/Group 1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Delete_TreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_TreeActionPerformed
          DeleteTree dlt = new DeleteTree() ;

        this.dispose();
        dlt.setVisible(true);
    }//GEN-LAST:event_Delete_TreeActionPerformed

    private void Add_TreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_TreeActionPerformed
        InsertData ins = new InsertData() ;
        this.dispose();
        ins.setVisible(true);
        
    }//GEN-LAST:event_Add_TreeActionPerformed

    private void Update_TreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_TreeActionPerformed
         Update_Tree upd = new Update_Tree() ;
        this.dispose();
        upd.setVisible(true);
    }//GEN-LAST:event_Update_TreeActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
        HomePage hm = new HomePage() ;
        this.dispose(); 
        hm.setVisible(true);
    }//GEN-LAST:event_Logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Tree;
    private javax.swing.JButton Delete_Tree;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton Update_Tree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
