/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tree;

/**
 *
 * @author Mahedi Hasan
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Badmin = new javax.swing.JButton();
        Buser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        exitbtn.setBackground(new java.awt.Color(0, 51, 51));
        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("Exit");
        exitbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        exitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbtn.setFocusable(false);
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn);
        exitbtn.setBounds(20, 10, 60, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("-OR-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(570, 250, 28, 15);

        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tree/Tree-icon.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 100, 80, 110);

        Badmin.setBackground(new java.awt.Color(153, 0, 0));
        Badmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Badmin.setForeground(new java.awt.Color(255, 255, 255));
        Badmin.setText("Admin");
        Badmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Badmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Badmin.setFocusPainted(false);
        Badmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BadminFocusGained(evt);
            }
        });
        Badmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BadminMouseClicked(evt);
            }
        });
        Badmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadminActionPerformed(evt);
            }
        });
        jPanel1.add(Badmin);
        Badmin.setBounds(600, 230, 130, 60);

        Buser.setBackground(new java.awt.Color(153, 0, 0));
        Buser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Buser.setForeground(new java.awt.Color(255, 255, 255));
        Buser.setText("User");
        Buser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Buser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buser.setFocusPainted(false);
        Buser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuserActionPerformed(evt);
            }
        });
        jPanel1.add(Buser);
        Buser.setBounds(440, 230, 130, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tree/ACmahhh.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadminActionPerformed
        // TODO add your handling code here:
        NewLogin login = new NewLogin() ;  
        this.dispose();
        login.setVisible(true);  
      
        
    }//GEN-LAST:event_BadminActionPerformed

    private void BuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuserActionPerformed
       this.dispose();
       FindTree find = new FindTree() ;
       find.setVisible(true);
    }//GEN-LAST:event_BuserActionPerformed

    private void BadminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BadminFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BadminFocusGained

    private void BadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BadminMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_BadminMouseClicked

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
       System.exit(1);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      HomePage home ;
      home = new HomePage() ;
      home.setVisible(true) ;
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Badmin;
    private javax.swing.JButton Buser;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
