/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

 */

package tree;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;






/**
 *
 * @author Mahedi Hasan
 */
public class Update_Tree extends javax.swing.JFrame {

    /**
     * Creates new form InsertData
     */
    public Update_Tree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b2btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updescription = new javax.swing.JTextArea();
        upbt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        uplocation = new javax.swing.JTextArea();
        upsrc = new javax.swing.JTextField();
        updbtn = new javax.swing.JButton();
        Atta = new javax.swing.JButton();
        upimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tree/Text-Edit-icon.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update Tree");

        b2btn.setBackground(new java.awt.Color(0, 51, 51));
        b2btn.setForeground(new java.awt.Color(255, 255, 255));
        b2btn.setText("Back");
        b2btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        b2btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2btn.setFocusable(false);
        b2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b2btn)
                .addGap(77, 77, 77)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Photo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Description");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Location");

        updescription.setColumns(20);
        updescription.setRows(5);
        updescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(updescription);

        upbt.setBackground(new java.awt.Color(0, 51, 0));
        upbt.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        upbt.setForeground(new java.awt.Color(255, 255, 255));
        upbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tree/search-icon (1).png"))); // NOI18N
        upbt.setText("Search");
        upbt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        upbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upbt.setFocusable(false);
        upbt.setIconTextGap(7);
        upbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upbtMouseClicked(evt);
            }
        });
        upbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upbtActionPerformed(evt);
            }
        });

        uplocation.setColumns(20);
        uplocation.setRows(5);
        jScrollPane2.setViewportView(uplocation);

        updbtn.setBackground(new java.awt.Color(0, 102, 51));
        updbtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        updbtn.setText("Update Tree");
        updbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        updbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updbtn.setFocusable(false);
        updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbtnActionPerformed(evt);
            }
        });

        Atta.setBackground(new java.awt.Color(0, 51, 0));
        Atta.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        Atta.setForeground(new java.awt.Color(255, 255, 255));
        Atta.setText("Attach Image");
        Atta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttaActionPerformed(evt);
            }
        });

        upimage.setBackground(new java.awt.Color(255, 255, 255));
        upimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Atta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(upsrc)
                                .addGap(18, 18, 18)
                                .addComponent(upbt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upbt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upsrc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(upimage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Atta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 110, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(928, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upbtMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_upbtMouseClicked

    private void upbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upbtActionPerformed
         Connection connection = null;
String connectionURL = "jdbc:mysql://localhost:3306/mahedi_khan";

ResultSet rs = null;
  PreparedStatement psmnt;
        psmnt = null;
FileInputStream fis;
try {


Class.forName("com.mysql.jdbc.Driver").newInstance();

connection = DriverManager.getConnection(connectionURL, "root", "");
 Statement st  ;
    st = connection.createStatement() ; 
    rs = st.executeQuery("select * from tms where Name='"+upsrc.getText()+"'") ;
     if(rs.next()){
         String name = rs.getString("Location") ;
         uplocation.setText(name);
         String description = rs.getString("Description") ;
         updescription.setText(description);
         byte[] img = rs.getBytes("Image") ;
         ImageIcon image = new ImageIcon(img) ;
         Image imgg = image.getImage() ;
         Image myimg = imgg.getScaledInstance(upimage.getWidth(), upimage.getHeight(), Image.SCALE_SMOOTH) ;
         ImageIcon newimg = new ImageIcon(myimg) ;
         upimage.setIcon(newimg);
        
     }
     else{
              JOptionPane.showMessageDialog(null,"Tree Does Not Exist");
     }
                     
}
catch(   ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex){
    JOptionPane.showMessageDialog(null,ex);
}

       
      
    }//GEN-LAST:event_upbtActionPerformed

    private void b2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2btnActionPerformed
         AdminHome ahm = new AdminHome() ;
       this.dispose();
       ahm.setVisible(true);
    }//GEN-LAST:event_b2btnActionPerformed

    private void updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbtnActionPerformed
       Connection connection = null;
String connectionURL = "jdbc:mysql://localhost:3306/mahedi_khan";

ResultSet rs = null;


  PreparedStatement psmnt;
        psmnt = null;
FileInputStream fis;
try {


Class.forName("com.mysql.jdbc.Driver").newInstance();

connection = DriverManager.getConnection(connectionURL, "root", "");
       Statement st  ;
    st = connection.createStatement() ; 
    rs = st.executeQuery("select * from tms where Name='"+upsrc.getText()+"'") ;
    boolean check =false;
    
    if(rs.next()){

      check = true ;
     
    }

 
 

if(check){
    if(filename == null){
    psmnt = (PreparedStatement) connection.prepareStatement("UPDATE tms SET Location =?, Description=? WHERE Name = '"+upsrc.getText()+"'");
 
//psmnt.setString(1,upsrc.getText());
psmnt.setString(1,uplocation.getText());
psmnt.setString(2,updescription.getText());
    
    }
    else{
    File image = new File(filename);
psmnt = (PreparedStatement) connection.prepareStatement("UPDATE tms SET Location =?, Description=?, Image=?   WHERE Name = '"+upsrc.getText()+"'");
 
//psmnt.setString(1,upsrc.getText());
psmnt.setString(1,uplocation.getText());
psmnt.setString(2,updescription.getText());
fis = new FileInputStream(image);
    
psmnt.setBinaryStream(3, (InputStream)fis, (int)(image.length()));
    }

int s = psmnt.executeUpdate();
if(s>0) {
      JOptionPane.showMessageDialog(null, "Tree has been Updated");
}
else {
      JOptionPane.showMessageDialog(null,"Tree has not been Updated, something is wrong");
}
}
else{
         JOptionPane.showMessageDialog(null, "The Tree Has Not Exist");
}
    }

// catch if found any exception during rum time.
catch (FileNotFoundException | ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
      JOptionPane.showMessageDialog(null, ex);
        }



finally {
    try {
        // close all the connections.
        connection.close();
        psmnt.close();
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null, ex);
    }
}

 
    }//GEN-LAST:event_updbtnActionPerformed

    private void AttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttaActionPerformed

        JFileChooser j = new JFileChooser() ;
        j.showOpenDialog(null) ;
        File f = j.getSelectedFile() ;
        filename = f.getAbsolutePath() ;
        // filenamee = filename ;
        ImageIcon icon = new ImageIcon(filename) ;
         Image image = icon.getImage().getScaledInstance(upimage.getWidth(), upimage.getHeight(), Image.SCALE_SMOOTH) ;
        ImageIcon nicon = new ImageIcon(image) ;
        upimage.setIcon(nicon);
    }//GEN-LAST:event_AttaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Tree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        Update_Tree ftree = new Update_Tree() ;
        ftree.setVisible(true);
        
         
 
         


    }
   String filename = null ;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atta;
    private javax.swing.JButton b2btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton upbt;
    private javax.swing.JButton updbtn;
    public javax.swing.JTextArea updescription;
    private javax.swing.JLabel upimage;
    public javax.swing.JTextArea uplocation;
    private javax.swing.JTextField upsrc;
    // End of variables declaration//GEN-END:variables
}
